
yamlname: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: sftp-deploy-actions/sftp-deploy@v1
        with:
          username: 'your_server_username'
          server: 'your_server_ip_or_domain'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './*'
          remote_path: '/var/www/html/' # Your web server path
